dist: xenial
sudo: required
services:
    - docker
    - xvfb

addons:
    chrome: stable

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - docker build -t tejozarkar/docker-angular -f Dockerfile.dev . 

script:
    - docker run -e CI=true -p 80:3000 tejozarkar/docker-angular npm run test